### Implemented from psuedocode in wikipedia: https://en.wikipedia.org/wiki/SHA-1

import hashlib
import sys


sys.path.insert(0, './lib')
from my_crypto_lib import *


key = b's3cr3t YELLOW SUMARINE'
message = b'Testing implementation of SHA1 MAC ...'
hashed = sha1_mac(key, message)

# Verify implementation of SHA1 is correct
h = hashlib.sha1(key + message)
assert (hashed == h.hexdigest())
print "Hash generated by built-in hashlib:",h.hexdigest()
print "Hash generated by implementation:",hashed
